### PR TITLE
Support OpenSSH2 key formats for all supported key algorithms

### PR DESCRIPTION
**Pull request by mc1arke**
Adds support got OpenSSH2 key formats for parsing ECDSA (all curves), RSA and DSA keys, alongside the existing Ed25519 key parsing

### CODE REVIEW

**Comment by kruton** [comment]
If you remove the values used in the Chinese Remainder Theorem (CRT)
calculation such as dP, dQ, qInv, etc. then signing with the key can't be
done with blinding. This would be bad given that it will then leak timing
info, so I would endeavor to keep those values needed for CRT.

**Comment by mc1arke** [comment]
Agreed. I'd actually switched that line to allow the equals comparison in my unit test to pass, rather than for any functional purpose. I'll go back and see whether I can add some logic for the new key format to use CRT (we _may_ get `P` and `Q`, so could calculate the other fields) thereby preventing any timing attack from using new format keys, otherwise I'll just switch my test to check the necessary values within the keys.

**Comment by mc1arke** [comment]
That's the 'old' key reverted to CRT, and new new format OpenSSH key converted to use CRT if the fields are provided.

**Comment by mc1arke** [comment]
@kruton Do you need any further changes on this PR?

**Comment by kruton** [comment]
Thanks for adding the parameter recovery. It looks good.

Could you add some tests to make sure that an RSA key without crt coeff and P can work and that an RSA key with crt coeff and P comes out as an RSAPrivateCrtKey. I'm not sure which one the added test for RSA in this PR covers.

**Pull request merged**
